### ISSUE TITLE
Is it possible to avoid substituting environment variables in the path?

### ISSUE THREAD

**Issue by fgimian** [gdivis/WindowsShortcutFactory#2]
Hey there, thank you so much for this incredible library!

Suppose we have a shortcut whose Target path contains an environment variable:

e.g.

![image](https://user-images.githubusercontent.com/1811813/169806409-6ad9e006-63c1-40bc-be80-132efb2290aa.png)

Using this library, I proceeded to print all properties of this shortcut:

```c#
        WindowsShortcut shortcut = WindowsShortcut.Load(
            @"C:\Users\Fots\Desktop\Windows Sandbox.lnk");

        Console.WriteLine($"Description = {shortcut.Description}");
        Console.WriteLine($"Path = {shortcut.Path}");
        Console.WriteLine($"Arguments = {shortcut.Arguments}");
        Console.WriteLine($"ShowCommand = {shortcut.ShowCommand}");
        Console.WriteLine($"IconLocation = {shortcut.IconLocation}");
```

However, the path is expanded and not printed with its original environment variable of `%windir%`:

e.g.

```
Description = Provides an environment to conveniently use untrusted software without repercussions on the host.
Path = C:\Windows\system32\WindowsSandbox.exe
Arguments =
ShowCommand = Normal
IconLocation = %windir%\system32\WindowsSandbox.exe
```

I observed a similar behaviour when using the `WScript.Shell` COM object to read the shortcut in PowerShell.  Thus, I'm not sure if this is something that can be avoided?

Having the original environment variable in the path as is done with the icon location would be ideal if that's possible.

Any ideas?

Thank you so much in advance
Fotis

**Comment by gdivis** [comment]
Thanks! It looks like it's just a matter of passing the right flag into [`IShellLink::GetPath`](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-getpath). I'll make that change as soon as I get a chance.

**Comment by fgimian** [comment]
> Thanks! It looks like it's just a matter of passing the right flag into [`IShellLink::GetPath`](https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nf-shobjidl_core-ishelllinkw-getpath). I'll make that change as soon as I get a chance.

Oh that's awesome!! Thank you so much, that would be incredible 😄

**Comment by gdivis** [comment]
Well that took longer than I expected to get to, but it's been published finally!

**Comment by fgimian** [comment]
> Well that took longer than I expected to get to, but it's been published finally!

Thanks so much, no rush at all.  As you've noticed, I haven't yet gotten to the hotkey implementation either as I've been pretty busy with a few other projects.  But it is still on my radar.

Thank you so much for your help!
Fotis
